### ISSUE TITLE
noob question: Better way to convert Any to my specific types?

### ISSUE THREAD

**Issue by cocodrino** [yhirose/go-peg#10]
Hi @yhirose , first I'm a bit newbie with go and I've some small troubles trying to translate this code from peg.js

```
document=text*
text = word / space / symbol
symbol = s:("." / "," / "¿" / "?"){return {type:"symbol",value:s}} 
word = w:(letter+){return {type:"word",value: w.join("")}}
space=s:" " {return {type:"space"}}
letter = [a-zA-Z0-9]
              
```

this is a not big deal, basically I want convert a hello world in something like
some test.

in

```js
[
   {
      "type": "word",
      "value": "some"
   },
   {
      "type": "space"
   },
   {
      "type": "word",
      "value": "test"
   },
   {
      "type": "symbol",
      "value": "."
   }
]

```

in go I'd like that the resulting type will be an Array of Element
this is my cod

```go

type Element struct {
	elementType string
	value string
}

func MyEjemplo() {
	parser, err := NewParser(`
		# Grammar for simple calculator...
		DOCUMENT <- TEXT*
		TEXT <- WORD / SPACE / SYMBOL
		SYMBOL <- < [.,?$=%()] > 
		WORD <- LETTER+
		SPACE <- ' '
		LETTER <- [a-zA-Z0-9]
	`)

	if err != nil{
		fmt.Println(err)
		return
	}

	g := parser.Grammar

	g["DOCUMENT"].Action = func(v *Values, d Any) (any Any, e error) {
		fmt.Println("running document")
		return &v.Vs,nil
	}

	g["SYMBOL"].Action = func(v *Values, d Any) (any Any, e error) {
		return &Element{elementType:"symbol",value:v.ToStr(0)},nil
	}
	g["WORD"].Action = func(v *Values, d Any) (any Any, e error) {
		return &Element{elementType:"word", value: v.S},nil
	}
	g["SPACE"].Action = func(v *Values, d Any) (any Any, e error) {
		return &Element{elementType:"space",value:" "},nil
	}

	input := "hola como estas"

	values, _ := parser.ParseAndGetValue(input, nil)

	//values type is Any, how simply convert this to []Element??

	//fmt.Println(results)


}
```

hope you can help me to understand a bit better this...thank you so much

**Comment by cocodrino** [comment]
right now I'm using this

```go
	values, _ := parser.ParseAndGetValue(input, nil)

	var results []Element
	for _,v := range values.([]Any){
		elemento := (v).(*Element)
		results = append(results,*elemento)
	}

	fmt.Printf("%v", results)
```

works...but it's the right way?...thank you!!!

**Comment by yhirose** [comment]
@cocodrino, I am not a Golang expert either. :)

How about this?

```go
	g := parser.Grammar

	g["DOCUMENT"].Action = func(v *Values, d Any) (any Any, e error) {
          fmt.Println("running document")
          results := make([]Element, 0, len(v.Vs))
          for _, v := range v.Vs {
            elemento := (v).(*Element)
            results = append(results, *elemento)
          }
          return results, nil
	}

	g["SYMBOL"].Action = func(v *Values, d Any) (any Any, e error) {
		return &Element{elementType:"symbol",value:v.Token()},nil
	}
	g["WORD"].Action = func(v *Values, d Any) (any Any, e error) {
		return &Element{elementType:"word", value: v.Token()},nil
	}
	g["SPACE"].Action = func(v *Values, d Any) (any Any, e error) {
		return &Element{elementType:"word", value: v.Token()},nil
	}

	input := "hola como estas"

	results, _ := parser.ParseAndGetValue(input, nil)

	fmt.Printf("%v", results)
```

**Comment by cocodrino** [comment]
thank you @yhirose , I ended with a similar implementation and I think it will work fine, I've a question...with 
https://pegjs.org/online I did something like this 

```
document=text*
text = word / space / symbol
symbol = s:("="/"$" /"." / "," / "¿" / "?"){return {type:"symbol",value:s}} 
word = w:(letter+){return {type:"word",data: w.join("")}}
space=s:" " {return {type:"space"}}
letter = [a-zA-Z0-9]
```

you can try for instance var1=hello and works great

with go-peg I did something similar but debugging, after parse the equal sign I get this error

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/yhirose/go-peg.(*Values).ToStr(...)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/ope.go:41
main.NewParsePronunciator.func2(0xc00052a120, 0x0, 0x0, 0x18, 0xc00052a120, 0xc00082b5e0, 0x0)
        /home/yo/Descargas/proj/go/gopronounciator/parser.go:50 +0xee
github.com/yhirose/go-peg.(*Rule).parseCore(0xc00008a240, 0x51337f, 0x2a, 0x18, 0xc00052a0c0, 0xc00082b5e0, 0x0, 0x0, 0xffffffffffffffff)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/rule.go:129 +0x44a
github.com/yhirose/go-peg.parse(0x5284c0, 0xc00008a240, 0x51337f, 0x2a, 0x18, 0xc00052a0c0, 0xc00082b5e0, 0x0, 0x0, 0xffffffffffffffff)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/ope.go:130 +0x98
github.com/yhirose/go-peg.(*Rule).parse(0xc00008a240, 0x51337f, 0x2a, 0x18, 0xc00052a0c0, 0xc00082b5e0, 0x0, 0x0, 0xffffffffffffffff)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/rule.go:103 +0x8d
github.com/yhirose/go-peg.(*reference).parseCore(0xc0000801c0, 0x51337f, 0x2a, 0x18, 0xc00052a0c0, 0xc00082b5e0, 0x0, 0x0, 0xffffffffffffffff)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/ope.go:529 +0x4bb
github.com/yhirose/go-peg.parse(0x528780, 0xc0000801c0, 0x51337f, 0x2a, 0x18, 0xc00052a0c0, 0xc00082b5e0, 0x0, 0x0, 0xffffffffffffffff)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/ope.go:130 +0x98
github.com/yhirose/go-peg.(*opeBase).parse(0xc0000801c0, 0x51337f, 0x2a, 0x18, 0xc00052a0c0, 0xc00082b5e0, 0x0, 0x0, 0x0)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/ope.go:156 +0x8d
github.com/yhirose/go-peg.(*prioritizedChoice).parseCore(0xc000067920, 0x51337f, 0x2a, 0x18, 0xc00052a060, 0xc00082b5e0, 0x0, 0x0, 0x5)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/ope.go:192 +0x1f6
github.com/yhirose/go-peg.parse(0x528740, 0xc000067920, 0x51337f, 0x2a, 0x18, 0xc00052a060, 0xc00082b5e0, 0x0, 0x0, 0x5)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/ope.go:130 +0x98
github.com/yhirose/go-peg.(*opeBase).parse(0xc000067920, 0x51337f, 0x2a, 0x18, 0xc00052a060, 0xc00082b5e0, 0x0, 0x0, 0x0)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/ope.go:156 +0x8d
github.com/yhirose/go-peg.(*Rule).parseCore(0xc00008a180, 0x51337f, 0x2a, 0x18, 0xc00050a060, 0xc00082b5e0, 0x0, 0x0, 0x5)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/rule.go:118 +0x176
github.com/yhirose/go-peg.parse(0x5284c0, 0xc00008a180, 0x51337f, 0x2a, 0x18, 0xc00050a060, 0xc00082b5e0, 0x0, 0x0, 0x5)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/ope.go:130 +0x98
github.com/yhirose/go-peg.(*Rule).parse(0xc00008a180, 0x51337f, 0x2a, 0x18, 0xc00050a060, 0xc00082b5e0, 0x0, 0x0, 0x5)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/rule.go:103 +0x8d
github.com/yhirose/go-peg.(*reference).parseCore(0xc000080070, 0x51337f, 0x2a, 0x18, 0xc00050a060, 0xc00082b5e0, 0x0, 0x0, 0x5)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/ope.go:529 +0x4bb
github.com/yhirose/go-peg.parse(0x528780, 0xc000080070, 0x51337f, 0x2a, 0x18, 0xc00050a060, 0xc00082b5e0, 0x0, 0x0, 0x5)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/ope.go:130 +0x98
github.com/yhirose/go-peg.(*opeBase).parse(0xc000080070, 0x51337f, 0x2a, 0x18, 0xc00050a060, 0xc00082b5e0, 0x0, 0x0, 0x0)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/ope.go:156 +0x8d
github.com/yhirose/go-peg.(*zeroOrMore).parseCore(0xc00000ad20, 0x51337f, 0x2a, 0x0, 0xc00050a060, 0xc00082b5e0, 0x0, 0x0, 0xc000090af8)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/ope.go:224 +0x112
github.com/yhirose/go-peg.parse(0x5288c0, 0xc00000ad20, 0x51337f, 0x2a, 0x0, 0xc00050a060, 0xc00082b5e0, 0x0, 0x0, 0x430d3f)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/ope.go:130 +0x98
github.com/yhirose/go-peg.(*opeBase).parse(0xc00000ad20, 0x51337f, 0x2a, 0x0, 0xc00050a060, 0xc00082b5e0, 0x0, 0x0, 0x0)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/ope.go:156 +0x8d
github.com/yhirose/go-peg.(*Rule).parseCore(0xc00008a0c0, 0x51337f, 0x2a, 0x0, 0xc00050a000, 0xc00082b5e0, 0x0, 0x0, 0x5e1ae0)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/rule.go:118 +0x176
github.com/yhirose/go-peg.parse(0x5284c0, 0xc00008a0c0, 0x51337f, 0x2a, 0x0, 0xc00050a000, 0xc00082b5e0, 0x0, 0x0, 0xc00082b5e0)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/ope.go:130 +0x98
github.com/yhirose/go-peg.(*Rule).parse(0xc00008a0c0, 0x51337f, 0x2a, 0x0, 0xc00050a000, 0xc00082b5e0, 0x0, 0x0, 0xc000090d48)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/rule.go:103 +0x8d
github.com/yhirose/go-peg.(*Rule).Parse(0xc00008a0c0, 0x51337f, 0x2a, 0x0, 0x0, 0x0, 0x0, 0xc000090f30, 0x4cf046, 0xc00000c030)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/rule.go:69 +0x176
github.com/yhirose/go-peg.(*Parser).ParseAndGetValue(0xc000067e00, 0x51337f, 0x2a, 0x0, 0x0, 0x8, 0x1f, 0x11, 0x7)
        /home/yo/Documentos/proyectos/go/src/github.com/yhirose/go-peg/parser.go:598 +0xbf
main.(*ParsePronunciator).getElements(0xc00000c028, 0x51337f, 0x2a, 0x30, 0x30, 0xc000067890)
        /home/yo/Descargas/proj/go/gopronounciator/parser.go:83 +0x65
main.pronounceOk(0x0, 0x51337f, 0x2a, 0x0, 0x2)
        /home/yo/Descargas/proj/go/gopronounciator/main.go:132 +0x6c
main.main()
        /home/yo/Descargas/proj/go/gopronounciator/main.go:219 +0x43
exit status 2
```

can you see what could be the error here? this works fine for single orations with words and spaces, but when I insert some symbol I get the error.

thank you so much @yhirose

**Comment by yhirose** [comment]
@cocodrino, can I see our current complete source code?

**Comment by cocodrino** [comment]
thank you so much for your help @yhirose ,I found the issue, I replace this

```go
	g["SYMBOL"].Action = func(v *Values, d Any) (any Any, e error) {
		return &Element{elementType:"symbol",value:v.ToStr(0)},nil
```

to this

```go
	g["SYMBOL"].Action = func(v *Values, d Any) (any Any, e error) {
		return &Element{elementType::"symbol",value:v.S},nil //using v.S directly
	}
```

and works great

I've a last question: what is the difference between use the token operator  (ej < [.,?!#$%&/()='¿¡{};:]  > ) or not use it [.,?!#$%&/()='¿¡{};:]  ???



thank you so much for your help and packages, has been really fun start making some basic parsers...
